name = "AINJuliaRegistry"
uuid = "2ee46816-d155-477a-8b1b-420be10adb15"
repo = "https://github.com/HITS-AIN/AINJuliaRegistry"
description = "Julia registry for AIN produced packaged"

[packages]
07f64c3a-9b30-4ec3-9543-9b5b1b58bbba = { name = "SDSS_RM_Resampler", path = "S/SDSS_RM_Resampler" }
2763b4c3-16b4-4cc4-aaa5-7caef3d341dd = { name = "ICCF", path = "I/ICCF" }
333a9a01-0e78-4d37-bce2-040f730ab5dc = { name = "ProbabilisticFluxVariationGradient", path = "P/ProbabilisticFluxVariationGradient" }
3ed8efa5-706a-4739-9884-79022218f524 = { name = "AdaGP", path = "A/AdaGP" }
4498ab02-56af-48f6-b5af-4c1c07c71523 = { name = "GPCC", path = "G/GPCC" }
4c3045de-0da2-483a-8ead-ab5165d83806 = { name = "GPLVMplusData", path = "G/GPLVMplusData" }
4ead5c4e-c2ff-4d62-91d1-2960feabfb2a = { name = "HITSOpenDayJuly2022", path = "H/HITSOpenDayJuly2022" }
514699ec-cad0-4573-b799-e90939df45ca = { name = "ExponentialExpectations", path = "E/ExponentialExpectations" }
53ca922f-95ab-4814-be4f-2c2ccfc107cd = { name = "JuliaDemoGP", path = "J/JuliaDemoGP" }
593bb313-7fc8-446a-96f6-bb1e55a541c0 = { name = "PFVG_AA2021", path = "P/PFVG_AA2021" }
643c7dc9-154b-47f5-a9a9-7aebf3d59150 = { name = "GPCCVirial", path = "G/GPCCVirial" }
6ae24528-df3b-47a6-8d0b-c8e9925c8a04 = { name = "GPCCData", path = "G/GPCCData" }
ad9bf4b2-67b2-497f-82b2-ca17e89facaf = { name = "DelayCorrectedPFVG", path = "D/DelayCorrectedPFVG" }
c0897b8e-83d0-4fb6-ae3b-cc8fb0b0b58e = { name = "FPW", path = "F/FPW" }
cff4ffb7-3881-4a2c-8cec-a201ef7afd5c = { name = "TransferFunctions", path = "T/TransferFunctions" }
d6555c65-c469-4a06-b862-e0078cd500ae = { name = "DelayCorrectedPFVGData", path = "D/DelayCorrectedPFVGData" }
dfcf6cff-d197-40c3-bbe5-65491765b9c2 = { name = "GPLVMplus", path = "G/GPLVMplus" }
e472fcb8-ab9f-4ff8-82d2-c5cadce53af3 = { name = "MiscUtil", path = "M/MiscUtil" }
