name = "AINJuliaRegistry"
uuid = "2ee46816-d155-477a-8b1b-420be10adb15"
repo = "https://github.com/HITS-AIN/AINJuliaRegistry"
description = "Julia registry for AIN produced packaged"

[packages]
2763b4c3-16b4-4cc4-aaa5-7caef3d341dd = { name = "ICCF", path = "I/ICCF" }
333a9a01-0e78-4d37-bce2-040f730ab5dc = { name = "ProbabilisticFluxVariationGradient", path = "P/ProbabilisticFluxVariationGradient" }
4ead5c4e-c2ff-4d62-91d1-2960feabfb2a = { name = "HITSOpenDayJuly2022", path = "H/HITSOpenDayJuly2022" }
593bb313-7fc8-446a-96f6-bb1e55a541c0 = { name = "PFVG_AA2021", path = "P/PFVG_AA2021" }
643c7dc9-154b-47f5-a9a9-7aebf3d59150 = { name = "GPCCVirial", path = "G/GPCCVirial" }
6ae24528-df3b-47a6-8d0b-c8e9925c8a04 = { name = "GPCCData", path = "G/GPCCData" }
99dd9245-5fd5-4439-81a6-2183e70e1908 = { name = "ConvolvedKernel", path = "C/ConvolvedKernel" }
cff4ffb7-3881-4a2c-8cec-a201ef7afd5c = { name = "TransferFunctions", path = "T/TransferFunctions" }
d2256c36-f6cb-4f2b-bb45-9577641c7b75 = { name = "FastParzenWindows", path = "F/FastParzenWindows" }
e472fcb8-ab9f-4ff8-82d2-c5cadce53af3 = { name = "MiscUtil", path = "M/MiscUtil" }
