name = "AINJuliaRegistry"
uuid = "2ee46816-d155-477a-8b1b-420be10adb15"
repo = "https://github.com/HITS-AIN/AINJuliaRegistry"
description = "Julia registry for AIN produced packaged"

[packages]
2763b4c3-16b4-4cc4-aaa5-7caef3d341dd = { name = "ICCF", path = "I/ICCF" }
333a9a01-0e78-4d37-bce2-040f730ab5dc = { name = "ProbabilisticFluxVariationGradient", path = "P/ProbabilisticFluxVariationGradient" }
4498ab02-56af-48f6-b5af-4c1c07c71523 = { name = "GPCC", path = "G/GPCC" }
4ead5c4e-c2ff-4d62-91d1-2960feabfb2a = { name = "HITSOpenDayJuly2022", path = "H/HITSOpenDayJuly2022" }
593bb313-7fc8-446a-96f6-bb1e55a541c0 = { name = "PFVG_AA2021", path = "P/PFVG_AA2021" }
640a3bb9-347f-47c9-97d8-5dcc1a651101 = { name = "ConvolvedGaussianProcesses", path = "C/ConvolvedGaussianProcesses" }
643c7dc9-154b-47f5-a9a9-7aebf3d59150 = { name = "GPCCVirial", path = "G/GPCCVirial" }
6ae24528-df3b-47a6-8d0b-c8e9925c8a04 = { name = "GPCCData", path = "G/GPCCData" }
8b4f48ce-6449-4e45-815e-453786827800 = { name = "SynthReverberationProblemsIS", path = "S/SynthReverberationProblemsIS" }
99dd9245-5fd5-4439-81a6-2183e70e1908 = { name = "ConvolvedKernel", path = "C/ConvolvedKernel" }
c0897b8e-83d0-4fb6-ae3b-cc8fb0b0b58e = { name = "FPW", path = "F/FPW" }
cff4ffb7-3881-4a2c-8cec-a201ef7afd5c = { name = "TransferFunctions", path = "T/TransferFunctions" }
e472fcb8-ab9f-4ff8-82d2-c5cadce53af3 = { name = "MiscUtil", path = "M/MiscUtil" }
